revert merge - integracao feita

diff --git a/robot_commands/vision b/robot_commands/vision
--- a/robot_commands/vision
+++ b/robot_commands/vision
@@ -4,12 +4,28 @@ cd ~/RoboFEI-HT_2023_SOFTWARE
 source install/setup.bash 
 
 
-while [[ $# -gt 0 ]]; do
-  case "$1" in
-    -d|--debug)
-      ros2 launch robot_bringup vision_bringup.launch.py log_level:='debug'
-      exit 1
-      ;;
-  esac
-done
-ros2 launch robot_bringup vision_bringup.launch.py
+if [ $# -gt 0 ] 
+    then
+        case "$1" in
+            -d)
+            ros2 launch robot_bringup vision_bringup.launch.py log_level:='debug'
+            ;;
+            -i)
+            ros2 launch robot_bringup vision_bringup.launch.py log_level:='info'
+            ;;
+            -w)
+            ros2 launch robot_bringup vision_bringup.launch.py log_level:='warn'
+            ;;
+            -e)
+            ros2 launch robot_bringup vision_bringup.launch.py log_level:='error'
+            ;;
+            -f)
+            ros2 launch robot_bringup vision_bringup.launch.py log_level:='fatal'
+            exit 1
+            ;;
+        esac
+fi
+if [ $1 -z ]
+  then
+    ros2 launch robot_bringup vision_bringup.launch.py log_level:='info'
+fi
